// utils/qrToken.js
//
// QR codes must never be trusted as-is. Every QR payload generated by
// this app is an HMAC-signed token, so the server can cryptographically
// verify it was issued by this system and has not been tampered with,
// even though the payload itself only contains a public identifier
// (member_uid or coupon code) — never points, coupons, or personal data
// for the member QR.
//
// Token format: base64url(payload).base64url(hmacHex)
// payload = JSON { t: 'member' | 'coupon', id: <uid or code>, iat: <ms> }

const crypto = require('crypto');
const config = require('../config');

function base64url(input) {
  return Buffer.from(input).toString('base64url');
}

function sign(payloadObj) {
  const payload = base64url(JSON.stringify(payloadObj));
  const hmac = crypto
    .createHmac('sha256', config.auth.qrSigningSecret)
    .update(payload)
    .digest('base64url');
  return `${payload}.${hmac}`;
}

/**
 * Verify a signed QR token. Returns the decoded payload object if valid,
 * or null if the token is malformed or the signature does not match.
 */
function verify(token) {
  if (typeof token !== 'string' || !token.includes('.')) return null;

  const [payload, providedHmac] = token.split('.');
  if (!payload || !providedHmac) return null;

  const expectedHmac = crypto
    .createHmac('sha256', config.auth.qrSigningSecret)
    .update(payload)
    .digest('base64url');

  const expectedBuf = Buffer.from(expectedHmac);
  const providedBuf = Buffer.from(providedHmac);

  if (expectedBuf.length !== providedBuf.length) return null;
  if (!crypto.timingSafeEqual(expectedBuf, providedBuf)) return null;

  try {
    return JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
  } catch {
    return null;
  }
}

function signMemberToken(memberUid) {
  return sign({ t: 'member', id: memberUid, iat: Date.now() });
}

function signCouponToken(couponCode) {
  return sign({ t: 'coupon', id: couponCode, iat: Date.now() });
}

module.exports = { sign, verify, signMemberToken, signCouponToken };