// utils/qrToken.js
//
// QR codes must never be trusted as-is. Every QR payload generated by
// this app is an HMAC-signed token, so the server can cryptographically
// verify it was issued by this system and has not been tampered with,
// even though the payload itself only contains a public identifier
// (member_uid or coupon code) — never points, coupons, or personal data
// for the member QR.
//
// Token format: base64url(payload).base64url(hmacHex)
// payload = JSON { t: 'member' | 'coupon', id: <uid or code>, iat: <ms>, exp?: <ms>, sid?: <sessionId> }

const crypto = require('crypto');
const config = require('../config');

function base64url(input) {
  return Buffer.from(input).toString('base64url');
}

function sign(payloadObj) {
  const payload = base64url(JSON.stringify(payloadObj));
  const hmac = crypto
    .createHmac('sha256', config.auth.qrSigningSecret)
    .update(payload)
    .digest('base64url');
  return `${payload}.${hmac}`;
}

/**
 * Verify a signed QR token. Returns the decoded payload object if valid,
 * or null if the token is malformed, signature doesn't match, or expired.
 */
function verify(token) {
  if (typeof token !== 'string' || !token.includes('.')) return null;

  const [payload, providedHmac] = token.split('.');
  if (!payload || !providedHmac) return null;

  const expectedHmac = crypto
    .createHmac('sha256', config.auth.qrSigningSecret)
    .update(payload)
    .digest('base64url');

  const expectedBuf = Buffer.from(expectedHmac);
  const providedBuf = Buffer.from(providedHmac);

  if (expectedBuf.length !== providedBuf.length) return null;
  if (!crypto.timingSafeEqual(expectedBuf, providedHmac)) return null;

  try {
    const decoded = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));

    // Check expiration if present
    if (decoded.exp && Date.now() > decoded.exp) {
      return null;
    }

    return decoded;
  } catch {
    return null;
  }
}

function signMemberToken(memberUid) {
  return sign({ t: 'member', id: memberUid, iat: Date.now() });
}

function signCouponToken(couponCode, expiresInMinutes = null) {
  const payload = { t: 'coupon', id: couponCode, iat: Date.now() };
  if (expiresInMinutes) {
    payload.exp = Date.now() + expiresInMinutes * 60 * 1000;
  }
  return sign(payload);
}

function signCouponSessionToken(sessionId, couponCode, expiresInMinutes) {
  return sign({
    t: 'coupon',
    id: couponCode,
    sid: sessionId,
    iat: Date.now(),
    exp: Date.now() + expiresInMinutes * 60 * 1000
  });
}

module.exports = {
  sign,
  verify,
  signMemberToken,
  signCouponToken,
  signCouponSessionToken
};